In [ ]:
 #temperature from 3 sensors over 5 days
import numpy as np
sensor_temps=np.array([

[72,70,71],#Day 1
[75,73,74],#Day 2
[68,67,69],#Day 3
[71,70,72],#Day 4
[74,72,73],#Day 5
])

print(sensor_temps)
print(sensor_temps.shape)



[[72 75 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
(5, 3)


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2
