In [ ]:
import numpy as np
a=np.array([1,7,8,9])
b=np.array([2,5,6,4])
print(a+b)

[ 3 12 14 13]


In [ ]:
#matrices#
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
#dot product#
import numpy as np
np.dot([3,4],[5,6])


np.int64(39)

In [ ]:
#probability#
import random
outcomes=["spam","not spam"]
print(random.choice(outcomes))

spam


In [ ]:
#statistics#
import numpy as np
scores=[99,88,86,97,93]
print(np.mean(scores))

92.6


In [ ]:
w=7
ir=0.2
for i in range(3):
  w=w-ir*2*w
  print(w)

4.199999999999999
2.5199999999999996
1.5119999999999998


In [21]:
file=open("attendance.txt","r")
file.write("priyanshu\n raaghu\n ashwini\n hanumanthi\n ashwini")
file.close
file=open("attendance.txt","r")
print(file.read())
file.close

FileNotFoundError: [Errno 2] No such file or directory: 'attendance.txt'